### ISSUE TITLE
Feature Request: Being Able to Move a Note to a Different Topic

### ISSUE THREAD

**Issue by atxsinn3r** [kitabatake/CodeReadingNote#1]
As a user, it would be super awesome if I could move a note to a different topic, because I consistently find myself reorganizing them. An example of moving a note is simply by drag and drop a note to a different topic (if that's technically possible).

**Comment by kitabatake** [comment]
Thank you for your valuable proposal!
I think the way of drag and drop to a topic may hard to notice for users. Then I will plant to implement it on the context menu(right-click on the TopicLine).

**Comment by atxsinn3r** [comment]
Sounds great. Thank you!!

**Comment by kitabatake** [comment]
Done #2
It will released in few days.
